@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Jul 20 10:47:37 +0800 2026
REM SW Build 6140274 on Thu May 22 00:12:29 MDT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim soc_simple_tb_behav -key {Behavioral:sim_1:Functional:soc_simple_tb} -tclbatch soc_simple_tb.tcl -view D:/cpu-design/miniRV/soc_simple_tb.wcfg -log simulate.log"
call xsim  soc_simple_tb_behav -key {Behavioral:sim_1:Functional:soc_simple_tb} -tclbatch soc_simple_tb.tcl -view D:/cpu-design/miniRV/soc_simple_tb.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
