# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_gpio_1/axi_gpio_1.xci
# IP: The module: 'axi_gpio_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_gpio_1/axi_gpio_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_gpio_1/axi_gpio_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_gpio_1/axi_gpio_1.xci
# IP: The module: 'axi_gpio_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_gpio_1/axi_gpio_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_gpio_1/axi_gpio_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
