# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/cpu-design/miniRV-with-SoC/miniRV.runs/synth_1/miniRV_SoC.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/cpu-design/miniRV-with-SoC/miniRV.cache/wt [current_project]
set_property parent.project_path D:/cpu-design/miniRV-with-SoC/miniRV.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/cpu-design/miniRV-with-SoC/miniRV.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files D:/cpu-design/miniRV-with-SoC/src/coe/mul_div_test.coe
add_files D:/cpu-design/miniRV-with-SoC/src/coe/lw.coe
add_files D:/cpu-design/miniRV-with-SoC/src/coe/pipeline_test.coe
read_verilog -library xil_defaultlib {
  D:/cpu-design/miniRV-with-SoC/src/rtl/ALU.v
  D:/cpu-design/miniRV-with-SoC/src/rtl/Controller.v
  D:/cpu-design/miniRV-with-SoC/src/rtl/DCache.v
  D:/cpu-design/miniRV-with-SoC/src/rtl/ForwardingUnit.v
  D:/cpu-design/miniRV-with-SoC/src/rtl/ICache.v
  D:/cpu-design/miniRV-with-SoC/src/rtl/MEXT.v
  D:/cpu-design/miniRV-with-SoC/src/rtl/MREQ.v
  D:/cpu-design/miniRV-with-SoC/src/rtl/RF.v
  D:/cpu-design/miniRV-with-SoC/src/rtl/SEXT.v
  D:/cpu-design/miniRV-with-SoC/src/rtl/axi_master.v
  D:/cpu-design/miniRV-with-SoC/src/rtl/cpu_core.v
  D:/cpu-design/miniRV-with-SoC/src/rtl/cpu_top.v
  D:/cpu-design/miniRV-with-SoC/src/rtl/display_wrap.v
  D:/cpu-design/miniRV-with-SoC/src/rtl/divider.v
  D:/cpu-design/miniRV-with-SoC/src/rtl/multiplier.v
  D:/cpu-design/miniRV-with-SoC/src/rtl/switch_and_led_wrap.v
  D:/cpu-design/miniRV-with-SoC/src/rtl/timer_wrap.v
  D:/cpu-design/miniRV-with-SoC/src/rtl/uart_wrap.v
  D:/cpu-design/miniRV-with-SoC/src/rtl/miniRV_SoC.v
}
read_ip -quiet D:/cpu-design/miniRV-with-SoC/src/rtl/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/cpu-design/miniRV-with-SoC/miniRV.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/cpu-design/miniRV-with-SoC/miniRV.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/cpu-design/miniRV-with-SoC/miniRV.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet D:/cpu-design/miniRV-with-SoC/src/rtl/ip/bram_axi/bram_axi.xci
set_property used_in_implementation false [get_files -all d:/cpu-design/miniRV-with-SoC/src/rtl/ip/bram_axi/bram_axi_ooc.xdc]

read_ip -quiet D:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_protocol_converter_0/axi_protocol_converter_0.xci
set_property used_in_implementation false [get_files -all d:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_protocol_converter_0/axi_protocol_converter_0_ooc.xdc]

read_ip -quiet D:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_gpio_0/axi_gpio_0.xci
set_property used_in_implementation false [get_files -all d:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_gpio_0/axi_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_gpio_0/axi_gpio_0_ooc.xdc]

read_ip -quiet D:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_uartlite_0/axi_uartlite_0.xci
set_property used_in_implementation false [get_files -all d:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_uartlite_0/axi_uartlite_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_uartlite_0/axi_uartlite_0_ooc.xdc]

read_ip -quiet D:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_gpio_1/axi_gpio_1.xci
set_property used_in_implementation false [get_files -all d:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_gpio_1/axi_gpio_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_gpio_1/axi_gpio_1_ooc.xdc]

read_ip -quiet D:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_gpio_2/axi_gpio_2.xci
set_property used_in_implementation false [get_files -all d:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_gpio_2/axi_gpio_2_board.xdc]
set_property used_in_implementation false [get_files -all d:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_gpio_2/axi_gpio_2_ooc.xdc]

read_ip -quiet D:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_gpio_3/axi_gpio_3.xci
set_property used_in_implementation false [get_files -all d:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_gpio_3/axi_gpio_3_board.xdc]
set_property used_in_implementation false [get_files -all d:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_gpio_3/axi_gpio_3_ooc.xdc]

read_ip -quiet D:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_crossbar_0/axi_crossbar_0.xci
set_property used_in_implementation false [get_files -all d:/cpu-design/miniRV-with-SoC/src/rtl/ip/axi_crossbar_0/axi_crossbar_0_ooc.xdc]

read_ip -quiet D:/cpu-design/miniRV-with-SoC/src/rtl/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all d:/cpu-design/miniRV-with-SoC/miniRV.gen/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/cpu-design/miniRV-with-SoC/src/xdc/clock.xdc
set_property used_in_implementation false [get_files D:/cpu-design/miniRV-with-SoC/src/xdc/clock.xdc]

read_xdc D:/cpu-design/miniRV-with-SoC/src/xdc/miniRV_SoC.xdc
set_property used_in_implementation false [get_files D:/cpu-design/miniRV-with-SoC/src/xdc/miniRV_SoC.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top miniRV_SoC -part xc7a35tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef miniRV_SoC.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file miniRV_SoC_utilization_synth.rpt -pb miniRV_SoC_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
